# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "PyCon UK 2023"

# When changing the year, please change it in the title, above. We can't use vars in vars.
con_year: 2023
con_start: Friday 22nd September
con_finish: Monday 25th September
con_financial_assistance_deadline: "XX:00 (Europe/London) on Someday, Nth Somemonth"

cfp_open: false
cfp_end: Friday 30th June

tickets_open: false

# Ticket prices should include VAT at 20%.
# If VAT is no longer at 20%, the ticket page needs updating to reflect that.
con_standard_ticket_price: £X
con_individual_ticket_price: £Y
con_unwaged_ticket_price: £Z

con_location: Cardiff City Hall
con_director: Ann Barr

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://2023.pyconuk.org" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
source: src
destination: build
markdown: kramdown

sass:
  style: "compact"

permalink: "/:year/:month/:title/"
